[package]
name = "rusta"
version = "0.1.0"
edition = "2021"

[features]
pi3 = []
pi4 = []
pi5 = []

[dependencies]
# Provides a tiny panic handler used by the bare‑metal examples
panic-halt = "0.2"

[profile.release]
panic = "abort"
