[build]
target = "aarch64-unknown-none"

[unstable]
build-std = ["core"]               # cargo check/build builds libcore for target

[target.aarch64-unknown-none]
rustflags = ["-C", "link-arg=-Tmemory.x"]
